<?php
        
/*
This file is part of Incipio.

Incipio is an enterprise resource planning for Junior Enterprise
Copyright (C) 2012-2014 Florian Lefevre.

Incipio is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Incipio is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with Incipio as the file LICENSE.  If not, see <http://www.gnu.org/licenses/>.
*/


namespace mgate\PersonneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{
    public function getIntervenantsParPromo()
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('m')->from('mgatePersonneBundle:Membre', 'm')
          ->innerJoin('m.missions', 'mi')
          ->orderBy('m.promotion', 'ASC');
        return $query->getQuery()->getResult();
    }
    
    /**
     * 
     * @return array
     */
    
    public function getMembresParPromo()
    {
        $entities = $this->findBy(array(), array('promotion' => 'desc'));
        $membresParMandat = array();
        foreach($entities as $membre){
            $promo = $membre->getPromotion();
            if(array_key_exists($promo, $membresParMandat))
                $membresParMandat[$promo][] = $membre;
            else
                $membresParMandat[$promo] = array($membre);
        }        
        return $membresParMandat;
    }
    
    public function getCotisants()
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('m')->from('mgatePersonneBundle:Membre', 'm')
          ->innerJoin('m.mandats', 'ma')
          ->innerJoin('ma.poste', 'p')
          ->where('p.intitule LIKE :membre')
          ->andWhere('ma.finMandat > CURRENT_DATE()')
          ->setParameter('membre', 'Membre');
        return $query->getQuery()->getResult();
    }
}
