<?php

namespace mgate\PersonneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProspectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectRepository extends EntityRepository
{
    
    public function ajaxSearch($nom)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('n')->from('mgatePersonneBundle:Prospect', 'n')
          ->where( $qb->expr()->like('n.nom', $qb->expr()->literal('%' . $nom . '%')) )
          ->getQuery();
        return $query->getResult();
    }
}
