<?php

namespace mgate\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubclassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubclassRepository extends EntityRepository
{
}
