<?php

namespace mgate\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CcRepository extends EntityRepository
{
    
    public function getEtudesCa()
    {
        
        $qb = $this->createQueryBuilder('cc');
        

            $query = $qb->select('cc')
                        //->from('mgateSuiviBundle:Cc', 'cc');
                        //->leftJoin('cc.etude', 'e');
                        //->addSelect('e')
                        //->where('e.cc IS NOT NULL')
                        ->addOrderBy('cc.dateSignature');
  
           
                  
                    
        return $query->getQuery()->getResult();;
    }
    
    
}
