<?php

namespace mgate\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudeRepository extends EntityRepository
{
    
    public function getEtudesCa()
    {
        
        $qb = $this->_em->createQueryBuilder();
        

            $query = $qb->select('e')
                        ->from('mgateSuiviBundle:Etude', 'e')
                        ->leftJoin('e.cc', 'cc')
                        //->addSelect('e')
                        ->where('e.cc IS NOT NULL')
                        ->addOrderBy('cc.dateSignature');
  
           
                  
                    
        return $query->getQuery()->getResult();;
    }
    
}
