<?php

namespace mgate\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudeRepository extends EntityRepository
{
}
