<?php

namespace mgate\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudeRepository extends EntityRepository
{
    public function findByNumero($numero)
    {
        $mandat = (int) ($numero / 100);
        $num = $numero % 100;

        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('e')
                    ->from('mgateSuiviBundle:Etude', 'e')
                    ->where("e.mandat = $mandat")
                    ->andWhere("e.num = $num");
                   
        return $query->getQuery()->getOneOrNullResult();
    }
    
    
    public function getEtudesCa()
    {
        
        $qb = $this->_em->createQueryBuilder();
        

            $query = $qb->select('e')
                        ->from('mgateSuiviBundle:Cc', 'cc')
                        ->leftJoin('cc.etude', 'e');
                        //->addSelect('e')
                        //->where('e.cc IS NOT NULL')
                        //->addOrderBy('cc.dateSignature');
  
           
                  
                    
        return $query->getQuery()->getResult();;
    }
    
    
}
