<?php

namespace mgate\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FactureVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupePhasesRepository extends EntityRepository
{
    public function getGroupePhasesByEtude(Etude $etude){
        $qb = $this->_em->createQueryBuilder();
        $query = $qb
                ->select('g')
                ->from('mgateSuiviBundle:GroupePhases', 'g')
                ->innerJoin('g.etude', 'e')
                ->where("e.id = :etudeID")
                ->orderBy('g.numero','ASC')
                ->setParameter('etudeID', $etude->getId());
        return $query;
        
    }
    
    
}
