<?php

namespace mgate\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RepartitionJEHRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepartitionJEHRepository extends EntityRepository
{
}
