<?php

namespace mgate\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getNotPersonne($personne)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('n')->from('mgateUserBundle:User', 'n')
          ->where('n.personne IS NULL');
        
        if($personne)
        {
          $query->orWhere('n.personne = :personne')
            ->setParameter('personne', $personne);
        }
        
        return $query;
    }
}
