<?php

namespace mgate\TresoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteDeFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BVRepository extends EntityRepository
{
    /**
     * 
     * @return array
     */
    public function findAllByMandat() {        
        $entities = $this->findBy(array(), array('mandat' => 'desc', 'dateDeVersement' => 'asc'));
        $bvsParMandat = array();
        foreach($entities as $bv){
            $mandat = $bv->getMandat();
            if(array_key_exists($mandat, $bvsParMandat))
                $bvsParMandat[$mandat][] = $bv;
            else
                $bvsParMandat[$mandat] = array($bv);
        }        
        return $bvsParMandat;
    }
    
    /**
     * Renvoie les bv d'un mois concerné
     * YEAR MONTH DAY sont défini dans DashBoardBundle/DQL (qui doit devenir FrontEndBundle)
     * @return array
     */
    public function findAllByMonth($month, $year, $trimestriel = false) {
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('b')
                     ->from('mgateTresoBundle:BV', 'b');
        if($trimestriel)
            $query->where("MONTH(b.dateDeVersement) >= $month")
                  ->andWhere("MONTH(b.dateDeVersement) < ($month + 2)");
        else
            $query->where("MONTH(b.dateDeVersement) = $month");
        
        $query->andWhere("YEAR(b.dateDeVersement) = $year")->orderBy("b.dateDeVersement");
        
        return $query->getQuery()->getResult();
    }
}
