<?php
        
/*
This file is part of Incipio.

Incipio is an enterprise resource planning for Junior Enterprise
Copyright (C) 2012-2014 Florian Lefevre.

Incipio is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

Incipio is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with Incipio as the file LICENSE.  If not, see <http://www.gnu.org/licenses/>.
*/


namespace mgate\TresoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CotisationURSSAFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotisationURSSAFRepository extends EntityRepository
{
    /**
     * Renvoie les cotisations pour une date donnée
     * YEAR MONTH DAY sont défini dans DashBoardBundle/DQL (qui doit devenir FrontEndBundle)
     * @return array
     */
    public function findAllByDate(\DateTime $date) {
        $qb = $this->_em->createQueryBuilder();
        
        $date = $date->format('Y-m-d');
      
        $query = $qb->select('c')
                     ->from('mgateTresoBundle:CotisationURSSAF', 'c')
                     ->where("'$date' >= c.dateDebut")
                     ->andWhere("'$date' <= c.dateFin"); 
                 
        return $query->getQuery()->getResult();;
    }
}
