<?php

namespace mgate\TresoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteDeFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{
    /**
     * Renvoie les facture d'achat ou de vente sur un mois selon la date d'emmision pour les factures d'achat et d'encaissement pour les factures de vente
     * YEAR MONTH DAY sont défini dans DashBoardBundle/DQL (qui doit devenir FrontEndBundle)
     * @return array
     */
    public function findAllTVAByMonth($type, $month, $year) {
        $date = ($type == 1 ? 'dateEmission' : 'dateVersement');
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select('f')
                     ->from('mgateTresoBundle:Facture', 'f')
                     ->where('f.type '.($type == 1 ? '=' : '>').' 1')
                     ->andWhere("MONTH(f.$date) = $month")
                     ->andWhere("YEAR(f.$date) = $year");    
                  
                    
        return $query->getQuery()->getResult();
    }
}
