<?php

namespace mgate\TresoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoteDeFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteDeFraisRepository extends EntityRepository
{
    /**
     * 
     * @return array
     */
    public function findAllByMandat() {        
        $entities = $this->findBy(array(), array('mandat' => 'desc', 'date' => 'asc'));
        $nfsParMandat = array();
        foreach($entities as $nf){
            $mandat = $nf->getMandat();
            if(array_key_exists($mandat, $nfsParMandat))
                $nfsParMandat[$mandat][] = $nf;
            else
                $nfsParMandat[$mandat] = array($nf);
        }        
        return $nfsParMandat;
    }
}
