<?php

namespace mgate\FormationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
    /**
     * 
     * @return array
     */
    public function findAllByMandat() {        
        $entities = $this->findBy(array(), array('mandat' => 'desc', 'dateDebut' => 'asc'));
        $formationsParMandat = array();
        foreach($entities as $formation){
            $mandat = $formation->getMandat();
            if(array_key_exists($mandat, $formationsParMandat))
                $formationsParMandat[$mandat][] = $formation;
            else
                $formationsParMandat[$mandat] = array($formation);
        }        
        return $formationsParMandat;
    }
}
